[package]
name = "psp22"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"
resolver = "2"

[dependencies]
startup = "0.1.1"
ink = { path = "../../ink" }

[lib]
name = "psp22"
path = "mod.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"rlib",
]
