[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
startup = "0.1.1"
ink = { path = "../ink" }
psp22 = { path = "../psp22" }

[profile.release]
panic = "abort"
lto = true