[package]
name = "ink"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"
resolver = "2"

[dependencies]
startup = "0.1.1"
lazy_static = "1.4.0"

[lib]
name = "ink"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"rlib",
]